2022-03-01 18:30:54,655 INFO    MainThread:1280 [wandb_setup.py:_flush():75] Loading settings from /opt/ml/.config/wandb/settings
2022-03-01 18:30:54,655 INFO    MainThread:1280 [wandb_setup.py:_flush():75] Loading settings from /opt/ml/code/git_bcnlp/special_mission/hyunah/wandb/settings
2022-03-01 18:30:54,655 INFO    MainThread:1280 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-01 18:30:54,655 INFO    MainThread:1280 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-01 18:30:54,655 INFO    MainThread:1280 [wandb_init.py:_log_setup():386] Logging user logs to /opt/ml/code/git_bcnlp/special_mission/hyunah/wandb/run-20220301_183054-34zo7vmu/logs/debug.log
2022-03-01 18:30:54,656 INFO    MainThread:1280 [wandb_init.py:_log_setup():387] Logging internal logs to /opt/ml/code/git_bcnlp/special_mission/hyunah/wandb/run-20220301_183054-34zo7vmu/logs/debug-internal.log
2022-03-01 18:30:54,656 INFO    MainThread:1280 [wandb_init.py:_jupyter_setup():336] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fc4d008e670>
2022-03-01 18:30:54,656 INFO    MainThread:1280 [wandb_init.py:init():420] calling init triggers
2022-03-01 18:30:54,656 INFO    MainThread:1280 [wandb_init.py:init():425] wandb.init called with sweep_config: {}
config: {}
2022-03-01 18:30:54,656 INFO    MainThread:1280 [wandb_init.py:init():471] starting backend
2022-03-01 18:30:54,656 INFO    MainThread:1280 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-01 18:30:54,674 INFO    MainThread:1280 [backend.py:ensure_launched():219] starting backend process...
2022-03-01 18:30:54,690 INFO    MainThread:1280 [backend.py:ensure_launched():224] started backend process with pid: 1319
2022-03-01 18:30:54,691 INFO    MainThread:1280 [wandb_init.py:init():480] backend started and connected
2022-03-01 18:30:54,711 INFO    MainThread:1280 [wandb_run.py:_label_probe_notebook():921] probe notebook
2022-03-01 18:30:54,712 INFO    MainThread:1280 [wandb_run.py:_label_probe_notebook():931] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-03-01 18:30:54,712 INFO    MainThread:1280 [wandb_init.py:init():550] updated telemetry
2022-03-01 18:30:54,740 INFO    MainThread:1280 [wandb_init.py:init():581] communicating current version
2022-03-01 18:30:55,581 INFO    MainThread:1280 [wandb_init.py:init():586] got version response 
2022-03-01 18:30:55,581 INFO    MainThread:1280 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-01 18:30:55,809 INFO    MainThread:1280 [wandb_init.py:init():624] starting run threads in backend
2022-03-01 18:30:58,785 INFO    MainThread:1280 [wandb_run.py:_console_start():1827] atexit reg
2022-03-01 18:30:58,785 INFO    MainThread:1280 [wandb_run.py:_redirect():1701] redirect: SettingsConsole.WRAP
2022-03-01 18:30:58,786 INFO    MainThread:1280 [wandb_run.py:_redirect():1738] Wrapping output streams.
2022-03-01 18:30:58,788 INFO    MainThread:1280 [wandb_run.py:_redirect():1762] Redirects installed.
2022-03-01 18:30:58,788 INFO    MainThread:1280 [wandb_init.py:init():651] run started, returning control to user process
2022-03-01 18:30:58,791 INFO    MainThread:1280 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-01 18:30:58,791 INFO    MainThread:1280 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-01 18:30:58,796 INFO    MainThread:1280 [wandb_init.py:_resume_backend():308] resuming backend
2022-03-01 18:30:58,797 INFO    MainThread:1280 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-01 18:30:58,797 INFO    MainThread:1280 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-01 18:30:58,802 INFO    MainThread:1280 [wandb_init.py:_resume_backend():308] resuming backend
2022-03-01 18:30:58,803 INFO    MainThread:1280 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-01 18:30:58,804 INFO    MainThread:1280 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-01 18:30:58,807 INFO    MainThread:1280 [wandb_init.py:_resume_backend():308] resuming backend
2022-03-01 18:30:58,808 INFO    MainThread:1280 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-01 18:30:58,808 INFO    MainThread:1280 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-01 18:30:58,813 INFO    MainThread:1280 [wandb_init.py:_resume_backend():308] resuming backend
2022-03-01 18:31:02,348 INFO    MainThread:1280 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-01 18:31:02,348 INFO    MainThread:1280 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-01 18:31:02,352 INFO    MainThread:1280 [wandb_init.py:_resume_backend():308] resuming backend
2022-03-01 18:31:02,353 INFO    MainThread:1280 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-01 18:31:02,353 INFO    MainThread:1280 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-01 18:31:02,358 INFO    MainThread:1280 [wandb_init.py:_resume_backend():308] resuming backend
2022-03-01 18:31:02,360 INFO    MainThread:1280 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-01 18:31:02,360 INFO    MainThread:1280 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-01 18:31:02,363 INFO    MainThread:1280 [wandb_init.py:_resume_backend():308] resuming backend
2022-03-01 18:31:02,365 INFO    MainThread:1280 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-01 18:31:02,365 INFO    MainThread:1280 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-01 18:31:02,369 INFO    MainThread:1280 [wandb_init.py:_resume_backend():308] resuming backend
2022-03-01 18:38:15,809 INFO    MainThread:1280 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-01 18:38:15,809 INFO    MainThread:1280 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-01 19:01:37,713 INFO    MainThread:1280 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 0
2022-03-01 19:01:37,714 INFO    MainThread:1280 [wandb_run.py:_restore():1769] restore
