2022-03-01 19:48:44,677 INFO    MainThread:1933 [wandb_setup.py:_flush():75] Loading settings from /opt/ml/.config/wandb/settings
2022-03-01 19:48:44,677 INFO    MainThread:1933 [wandb_setup.py:_flush():75] Loading settings from /opt/ml/code/git_bcnlp/special_mission/hyunah/wandb/settings
2022-03-01 19:48:44,677 INFO    MainThread:1933 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-01 19:48:44,677 INFO    MainThread:1933 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-01 19:48:44,678 INFO    MainThread:1933 [wandb_init.py:_log_setup():386] Logging user logs to /opt/ml/code/git_bcnlp/special_mission/hyunah/wandb/run-20220301_194844-151a8pkt/logs/debug.log
2022-03-01 19:48:44,678 INFO    MainThread:1933 [wandb_init.py:_log_setup():387] Logging internal logs to /opt/ml/code/git_bcnlp/special_mission/hyunah/wandb/run-20220301_194844-151a8pkt/logs/debug-internal.log
2022-03-01 19:48:44,678 INFO    MainThread:1933 [wandb_init.py:_jupyter_setup():336] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fa762124970>
2022-03-01 19:48:44,678 INFO    MainThread:1933 [wandb_init.py:init():420] calling init triggers
2022-03-01 19:48:44,678 INFO    MainThread:1933 [wandb_init.py:init():425] wandb.init called with sweep_config: {}
config: {}
2022-03-01 19:48:44,678 INFO    MainThread:1933 [wandb_init.py:init():471] starting backend
2022-03-01 19:48:44,678 INFO    MainThread:1933 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-01 19:48:44,692 INFO    MainThread:1933 [backend.py:ensure_launched():219] starting backend process...
2022-03-01 19:48:44,710 INFO    MainThread:1933 [backend.py:ensure_launched():224] started backend process with pid: 1972
2022-03-01 19:48:44,711 INFO    MainThread:1933 [wandb_init.py:init():480] backend started and connected
2022-03-01 19:48:44,731 INFO    MainThread:1933 [wandb_run.py:_label_probe_notebook():921] probe notebook
2022-03-01 19:48:44,732 INFO    MainThread:1933 [wandb_run.py:_label_probe_notebook():931] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-03-01 19:48:44,732 INFO    MainThread:1933 [wandb_init.py:init():550] updated telemetry
2022-03-01 19:48:44,759 INFO    MainThread:1933 [wandb_init.py:init():581] communicating current version
2022-03-01 19:48:45,593 INFO    MainThread:1933 [wandb_init.py:init():586] got version response 
2022-03-01 19:48:45,593 INFO    MainThread:1933 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-01 19:48:45,824 INFO    MainThread:1933 [wandb_init.py:init():624] starting run threads in backend
2022-03-01 19:48:48,823 INFO    MainThread:1933 [wandb_run.py:_console_start():1827] atexit reg
2022-03-01 19:48:48,824 INFO    MainThread:1933 [wandb_run.py:_redirect():1701] redirect: SettingsConsole.WRAP
2022-03-01 19:48:48,824 INFO    MainThread:1933 [wandb_run.py:_redirect():1738] Wrapping output streams.
2022-03-01 19:48:48,825 INFO    MainThread:1933 [wandb_run.py:_redirect():1762] Redirects installed.
2022-03-01 19:48:48,825 INFO    MainThread:1933 [wandb_init.py:init():651] run started, returning control to user process
2022-03-01 19:48:48,828 INFO    MainThread:1933 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-01 19:48:48,828 INFO    MainThread:1933 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-01 19:48:48,833 INFO    MainThread:1933 [wandb_init.py:_resume_backend():308] resuming backend
2022-03-01 19:48:48,834 INFO    MainThread:1933 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-01 19:48:48,834 INFO    MainThread:1933 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-01 19:48:48,839 INFO    MainThread:1933 [wandb_init.py:_resume_backend():308] resuming backend
2022-03-01 19:48:48,841 INFO    MainThread:1933 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-01 19:48:48,841 INFO    MainThread:1933 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-01 19:48:48,846 INFO    MainThread:1933 [wandb_init.py:_resume_backend():308] resuming backend
2022-03-01 19:48:48,847 INFO    MainThread:1933 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-01 19:48:48,847 INFO    MainThread:1933 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-01 19:48:48,853 INFO    MainThread:1933 [wandb_init.py:_resume_backend():308] resuming backend
2022-03-01 19:48:52,278 INFO    MainThread:1933 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-01 19:48:52,278 INFO    MainThread:1933 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-01 19:48:52,282 INFO    MainThread:1933 [wandb_init.py:_resume_backend():308] resuming backend
2022-03-01 19:48:52,283 INFO    MainThread:1933 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-01 19:48:52,283 INFO    MainThread:1933 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-01 19:48:52,289 INFO    MainThread:1933 [wandb_init.py:_resume_backend():308] resuming backend
2022-03-01 19:48:52,297 INFO    MainThread:1933 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-01 19:48:52,297 INFO    MainThread:1933 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-01 19:48:52,301 INFO    MainThread:1933 [wandb_init.py:_resume_backend():308] resuming backend
2022-03-01 19:48:52,303 INFO    MainThread:1933 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-01 19:48:52,303 INFO    MainThread:1933 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-01 19:48:52,307 INFO    MainThread:1933 [wandb_init.py:_resume_backend():308] resuming backend
2022-03-01 20:09:35,684 INFO    MainThread:1933 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-01 20:09:35,684 INFO    MainThread:1933 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-01 20:09:46,079 INFO    MainThread:1933 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 0
2022-03-01 20:09:46,080 INFO    MainThread:1933 [wandb_run.py:_restore():1769] restore
